-- MySQL Script generated by MySQL Workbench
-- Sun 22 Oct 2017 02:57:31 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DataType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DataType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DataType` (
  `idDataType` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idDataType`),
  UNIQUE INDEX `idDataType_UNIQUE` (`idDataType` ASC))
ENGINE = InnoDB
COMMENT = 'There are three types of probe/gallery. Image. Image_Description, and Description.';


-- -----------------------------------------------------
-- Table `mydb`.`Experiments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Experiments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Experiments` (
  `idExperiments` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(200) NULL,
  `idDataType_Probe` INT NOT NULL,
  `idDataType_Gallery` INT NOT NULL,
  PRIMARY KEY (`idExperiments`),
  UNIQUE INDEX `idExperiments_UNIQUE` (`idExperiments` ASC),
  INDEX `idDataType_Probe_idx` (`idDataType_Probe` ASC),
  INDEX `idDataType_Gallery_idx` (`idDataType_Gallery` ASC),
  CONSTRAINT `idDataType_Gallery`
    FOREIGN KEY (`idDataType_Gallery`)
    REFERENCES `mydb`.`DataType` (`idDataType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idDataType_Probe`
    FOREIGN KEY (`idDataType_Probe`)
    REFERENCES `mydb`.`DataType` (`idDataType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contains the experiment description, and probe and gallery type.';


-- -----------------------------------------------------
-- Table `mydb`.`Participants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Participants` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Participants` (
  `idParticipants` INT NOT NULL AUTO_INCREMENT,
  `UUID` CHAR(36) NOT NULL,
  `Created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idExperiments` INT NOT NULL,
  PRIMARY KEY (`idParticipants`),
  UNIQUE INDEX `idParticipants_UNIQUE` (`idParticipants` ASC),
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC),
  INDEX `idExperiments_idx` (`idExperiments` ASC),
  CONSTRAINT `idExperiments`
    FOREIGN KEY (`idExperiments`)
    REFERENCES `mydb`.`Experiments` (`idExperiments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'The list of participants, their creation timestamp, and if they have completed the task.';

SET SQL_MODE = '';
GRANT USAGE ON *.* TO q3Hb9VXG;
 DROP USER q3Hb9VXG;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'q3Hb9VXG' IDENTIFIED BY 'TxS4B7K7';

GRANT SELECT ON TABLE `mydb`.* TO 'q3Hb9VXG';
GRANT SELECT ON TABLE `mydb`.`DataType` TO 'q3Hb9VXG';
GRANT SELECT ON TABLE `mydb`.`Participants` TO 'q3Hb9VXG';
GRANT INSERT ON TABLE `mydb`.`Participants` TO 'q3Hb9VXG';
SET SQL_MODE = '';
GRANT USAGE ON *.* TO brichar1;
 DROP USER brichar1;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'brichar1' IDENTIFIED BY 'himom';

GRANT ALL, CREATE, DROP, GRANT OPTION, REFERENCES, ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, TRIGGER ON TABLE `mydb`.`DataType` TO 'brichar1';
GRANT ALL, CREATE, DROP, GRANT OPTION, REFERENCES, ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, TRIGGER ON TABLE `mydb`.`Experiments` TO 'brichar1';
GRANT ALL, CREATE, DROP, GRANT OPTION, REFERENCES, ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, TRIGGER ON TABLE `mydb`.`Participants` TO 'brichar1';
GRANT INSERT ON TABLE `mydb`.`Participants` TO 'brichar1';
GRANT SELECT ON TABLE `mydb`.* TO 'brichar1';
GRANT SELECT ON TABLE `mydb`.`DataType` TO 'brichar1';
GRANT SELECT ON TABLE `mydb`.`Participants` TO 'brichar1';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`DataType`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`DataType` (`idDataType`, `Description`) VALUES (0, 'Image');
INSERT INTO `mydb`.`DataType` (`idDataType`, `Description`) VALUES (1, 'Description');
INSERT INTO `mydb`.`DataType` (`idDataType`, `Description`) VALUES (2, 'Image and Description');

COMMIT;

